# national data cleaning

In [2]:
# dependencies and make sure i'm in the same dir as this notebook
import pandas as pd
import os
my_dir = os.path.dirname(os.path.abspath('__file__'))
os.chdir(my_dir)

In [3]:
# clean and transform house price index
hpi_csv = 'data/uncleaned data/national data/zillow_hpi_case_shiller_us.csv'
hpi_df = pd.read_csv(hpi_csv)

hpi_df['observation_date'] = pd.to_datetime(hpi_df['observation_date'])
filtered_hpi_df = hpi_df[hpi_df['observation_date'].dt.strftime('%m-%d') == '12-01']
filtered_hpi_df['observation_date']=filtered_hpi_df['observation_date'].dt.year
filtered_hpi_df.rename(columns = {'observation_date':'year'}, inplace = True)
filtered_hpi_df['Z_YOY_change'] = filtered_hpi_df['USAUCSFRCONDOSMSAMID'].pct_change(periods=1) * 100
filtered_hpi_df['CS_YOY_change'] = filtered_hpi_df['CSUSHPINSA'].pct_change(periods=1) * 100
filtered_hpi_df.rename(columns = {'USAUCSFRCONDOSMSAMID':'zillow_index'}, inplace = True)
filtered_hpi_df.rename(columns = {'CSUSHPINSA':'case_shiller_index'}, inplace = True)
print(filtered_hpi_df)

     year  zillow_index  case_shiller_index  Z_YOY_change  CS_YOY_change
11   1987           NaN              68.342           NaN            NaN
23   1988           NaN              73.278           NaN       7.222499
35   1989           NaN              76.497           NaN       4.392860
47   1990           NaN              75.972           NaN      -0.686301
59   1991           NaN              75.843           NaN      -0.169799
71   1992           NaN              76.463           NaN       0.817478
83   1993           NaN              78.112           NaN       2.156599
95   1994           NaN              80.077           NaN       2.515619
107  1995           NaN              81.513           NaN       1.793274
119  1996           NaN              83.489           NaN       2.424153
131  1997           NaN              86.847           NaN       4.022087
143  1998           NaN              92.442           NaN       6.442364
155  1999           NaN              99.542           NaN       7.680492
167  2000   117576.3907             108.791           NaN       9.291555
179  2001   126000.1794             116.056      7.164524       6.677942
191  2002   135041.2280             127.151      7.175425       9.560040
203  2003   145770.5011             139.628      7.945183       9.812742
215  2004   161549.9132             158.670     10.824832      13.637666
227  2005   180559.7907             180.107     11.767185      13.510430
239  2006   189688.8617             183.230      5.055982       1.733969
251  2007   185533.7198             173.338     -2.190504      -5.398679
263  2008   168227.8496             152.545     -9.327615     -11.995639
275  2009   156506.6638             146.664     -6.967447      -3.855256
287  2010   151559.9928             140.632     -3.160678      -4.112802
299  2011   144126.5765             135.169     -4.904603      -3.884607
311  2012   149115.5613             143.868      3.461530       6.435647
323  2013   161836.3813             159.280      8.530847      10.712598
335  2014   171019.9100             166.462      5.674576       4.509041
347  2015   182816.8586             175.119      6.897997       5.200586
359  2016   193706.7216             184.407      5.956706       5.303822
371  2017   207144.3732             195.852      6.937112       6.206380
383  2018   220292.8822             204.709      6.347510       4.522292
395  2019   231752.2874             212.251      5.201895       3.684254
407  2020   254729.7956             234.405      9.914685      10.437642
419  2021   297029.6499                 NaN     16.605774       0.000000

/var/folders/hl/p3c4xh5x4nv00kvc7sckx1040000gn/T/ipykernel_49428/2587707951.py:5: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  hpi_df['observation_date'] = pd.to_datetime(hpi_df['observation_date'])
/var/folders/hl/p3c4xh5x4nv00kvc7sckx1040000gn/T/ipykernel_49428/2587707951.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_hpi_df['observation_date']=filtered_hpi_df['observation_date'].dt.year
/var/folders/hl/p3c4xh5x4nv00kvc7sckx1040000gn/T/ipykernel_49428/2587707951.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_hpi_df.rename(columns = {'observation_date':'year'}, inplace = True)
/var/folders/hl/p3c4xh5x4nv00kvc7sckx1040000gn/T/ipykernel_49428/2587707951.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_hpi_df['Z_YOY_change'] = filtered_hpi_df['USAUCSFRCONDOSMSAMID'].pct_change(periods=1) * 100
/var/folders/hl/p3c4xh5x4nv00kvc7sckx1040000gn/T/ipykernel_49428/2587707951.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_hpi_df['CS_YOY_change'] = filtered_hpi_df['CSUSHPINSA'].pct_change(periods=1) * 100
/var/folders/hl/p3c4xh5x4nv00kvc7sckx1040000gn/T/ipykernel_49428/2587707951.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_hpi_df.rename(columns = {'USAUCSFRCONDOSMSAMID':'zillow_index'}, inplace = True)
/var/folders/hl/p3c4xh5x4nv00kvc7sckx1040000gn/T/ipykernel_49428/2587707951.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_hpi_df.rename(columns = {'CSUSHPINSA':'case_shiller_index'}, inplace = True)

In [4]:
# clean and transform all transactions hpi
alltran_csv = 'data/uncleaned data/national data/all_transactions_hpi_us.csv'
alltran_df = pd.read_csv(alltran_csv)

alltran_df['observation_date'] = pd.to_datetime(alltran_df['observation_date'])
filtered_alltran_df = alltran_df[alltran_df['observation_date'].dt.strftime('%m-%d') == '10-01']
filtered_alltran_df['observation_date']=filtered_alltran_df['observation_date'].dt.year
filtered_alltran_df.rename(columns = {'observation_date':'year'}, inplace = True)
filtered_alltran_df['YOY_change'] = filtered_alltran_df['USSTHPI'].pct_change(periods=1) * 100
print(filtered_alltran_df)

     year  USSTHPI  YOY_change
3    1975    62.24         NaN
7    1976    67.24    8.033419
11   1977    77.19   14.797739
15   1978    87.48   13.330742
19   1979    98.24   12.299954
23   1980   104.59    6.463762
27   1981   107.47    2.753609
31   1982   111.69    3.926677
35   1983   117.65    5.336198
39   1984   123.16    4.683383
43   1985   130.18    5.699903
47   1986   139.68    7.297588
51   1987   147.29    5.448167
55   1988   155.58    5.628352
59   1989   164.31    5.611261
63   1990   166.30    1.211125
67   1991   171.49    3.120866
71   1992   175.62    2.408304
75   1993   180.28    2.653456
79   1994   183.10    1.564233
83   1995   191.43    4.549427
87   1996   196.27    2.528339
91   1997   204.88    4.386814
95   1998   215.25    5.061499
99   1999   225.85    4.924506
103  2000   241.84    7.079920
107  2001   259.05    7.116275
111  2002   276.42    6.705269
115  2003   295.71    6.978511
119  2004   326.26   10.331068
123  2005   362.93   11.239502
127  2006   379.36    4.527044
131  2007   375.07   -1.130852
135  2008   348.25   -7.150665
139  2009   330.19   -5.185930
143  2010   324.11   -1.841364
147  2011   313.32   -3.329117
151  2012   315.19    0.596834
155  2013   328.85    4.333894
159  2014   345.67    5.114794
163  2015   363.12    5.048167
167  2016   382.94    5.458251
171  2017   403.79    5.444717
175  2018   423.58    4.901062
179  2019   444.90    5.033288
183  2020   472.64    6.235109

/var/folders/hl/p3c4xh5x4nv00kvc7sckx1040000gn/T/ipykernel_49428/2609247329.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_alltran_df['observation_date']=filtered_alltran_df['observation_date'].dt.year
/var/folders/hl/p3c4xh5x4nv00kvc7sckx1040000gn/T/ipykernel_49428/2609247329.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_alltran_df.rename(columns = {'observation_date':'year'}, inplace = True)
/var/folders/hl/p3c4xh5x4nv00kvc7sckx1040000gn/T/ipykernel_49428/2609247329.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_alltran_df['YOY_change'] = filtered_alltran_df['USSTHPI'].pct_change(periods=1) * 100

In [5]:
# read unemployment and only keep the average
unemp_csv = 'data/uncleaned data/national data/unemployment_in_us.csv'
unemp_df = pd.read_csv(unemp_csv)
unemp_df = unemp_df[['year', 'Year_Average']]
unemp_df.rename(columns = {'Year_Average':'Unemployment_Year_Avg'}, inplace = True)
print(unemp_df)

    year  Unemployment_Year_Avg
0   1984                    7.7
1   1985                    7.2
2   1986                    6.7
3   1987                    6.2
4   1988                    5.5
5   1989                    5.4
6   1990                    5.9
7   1991                    6.9
8   1992                    7.4
9   1993                    6.9
10  1994                    6.1
11  1995                    5.6
12  1996                    5.5
13  1997                    5.0
14  1998                    4.5
15  1999                    4.2
16  2000                    4.0
17  2001                    5.0
18  2002                    5.9
19  2003                    5.8
20  2004                    5.6
21  2005                    5.1
22  2006                    4.6
23  2007                    4.8
24  2008                    6.2
25  2009                    8.9
26  2010                    9.6
27  2011                    8.8
28  2012                    8.1
29  2013                    7.4
30  2014                    6.1
31  2015                    5.4
32  2016                    4.8
33  2017                    4.4
34  2018                    4.0
35  2019                    3.8
36  2020                    5.1
37  2021                    5.1
38  2022                    3.8
39  2023                    3.4

In [6]:
# read recession
recess_csv = 'data/uncleaned data/national data/recessionflag.csv'
recess_df = pd.read_csv(recess_csv)
recess_df['DATE'] = pd.to_datetime(recess_df['DATE'])
filtered_recess_df = recess_df[recess_df['DATE'].dt.strftime('%m-%d') == '10-01']
filtered_recess_df['DATE']=filtered_recess_df['DATE'].dt.year
filtered_recess_df.rename(columns = {'DATE':'year'}, inplace = True)
filtered_recess_df.rename(columns = {'JHDUSRGDPBR':'recession'}, inplace = True)
print(filtered_recess_df)

     year  recession
0    2067          0
4    2068          0
8    2069          1
12   2070          1
16   2071          0
20   2072          0
24   1973          1
28   1974          1
32   1975          0
36   1976          0
40   1977          0
44   1978          0
48   1979          1
52   1980          0
56   1981          1
60   1982          0
64   1983          0
68   1984          0
72   1985          0
76   1986          0
80   1987          0
84   1988          0
88   1989          1
92   1990          1
96   1991          0
100  1992          0
104  1993          0
108  1994          0
112  1995          0
116  1996          0
120  1997          0
124  1998          0
128  1999          0
132  2000          0
136  2001          0
140  2002          0
144  2003          0
148  2004          0
152  2005          0
156  2006          0
160  2007          1
164  2008          1
168  2009          0
172  2010          0
176  2011          0
180  2012          0
184  2013          0
188  2014          0
192  2015          0
196  2016          0
200  2017          0
204  2018          0
208  2019          0
212  2020          0
216  2021          0

/var/folders/hl/p3c4xh5x4nv00kvc7sckx1040000gn/T/ipykernel_49428/2847561689.py:4: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  recess_df['DATE'] = pd.to_datetime(recess_df['DATE'])
/var/folders/hl/p3c4xh5x4nv00kvc7sckx1040000gn/T/ipykernel_49428/2847561689.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_recess_df['DATE']=filtered_recess_df['DATE'].dt.year
/var/folders/hl/p3c4xh5x4nv00kvc7sckx1040000gn/T/ipykernel_49428/2847561689.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_recess_df.rename(columns = {'DATE':'year'}, inplace = True)
/var/folders/hl/p3c4xh5x4nv00kvc7sckx1040000gn/T/ipykernel_49428/2847561689.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_recess_df.rename(columns = {'JHDUSRGDPBR':'recession'}, inplace = True)

In [7]:
# read federal funds rate
fed_csv = 'data/uncleaned data/national data/yearly_fed_rates_mean.csv'
fed_df = pd.read_csv(fed_csv)
fed_df.rename(columns = {'YEAR':'year'}, inplace = True)
print(fed_df)

    year  avg_rate_for_year
0   1954           1.008333
1   1955           1.785000
2   1956           2.728333
3   1957           3.105000
4   1958           1.572500
..   ...                ...
65  2019           2.158333
66  2020           0.375833
67  2021           0.080000
68  2022           1.683333
69  2023           4.516667

[70 rows x 2 columns]

In [8]:
# merge all the data and save as csv
merged_df = pd.merge(filtered_hpi_df, filtered_alltran_df, on = 'year', how = 'outer')
merged_df = pd.merge(merged_df, unemp_df, on = 'year', how = 'outer')
merged_df = pd.merge(merged_df, filtered_recess_df, on = 'year', how = 'outer')
merged_df = pd.merge(merged_df, fed_df, on = 'year', how = 'outer')
print(merged_df)

    year  zillow_index  case_shiller_index  Z_YOY_change  CS_YOY_change
0   1987           NaN              68.342           NaN            NaN  \
1   1988           NaN              73.278           NaN       7.222499
2   1989           NaN              76.497           NaN       4.392860
3   1990           NaN              75.972           NaN      -0.686301
4   1991           NaN              75.843           NaN      -0.169799
..   ...           ...                 ...           ...            ...
71  1968           NaN                 NaN           NaN            NaN
72  1969           NaN                 NaN           NaN            NaN
73  1970           NaN                 NaN           NaN            NaN
74  1971           NaN                 NaN           NaN            NaN
75  1972           NaN                 NaN           NaN            NaN

    USSTHPI  YOY_change  Unemployment_Year_Avg  recession  avg_rate_for_year
0    147.29    5.448167                    6.2        0.0           6.657500
1    155.58    5.628352                    5.5        0.0           7.568333
2    164.31    5.611261                    5.4        1.0           9.216667
3    166.30    1.211125                    5.9        1.0           8.099167
4    171.49    3.120866                    6.9        0.0           5.687500
..      ...         ...                    ...        ...                ...
71      NaN         NaN                    NaN        NaN           5.659167
72      NaN         NaN                    NaN        NaN           8.204167
73      NaN         NaN                    NaN        NaN           7.183333
74      NaN         NaN                    NaN        NaN           4.662500
75      NaN         NaN                    NaN        NaN           4.434167

[76 rows x 10 columns]

In [9]:
merged_df = merged_df.sort_values(by='year', ascending = True)
merged_df = merged_df[merged_df['year']<=2023]

In [10]:
merged_df.head()

,year,zillow_index,case_shiller_index,Z_YOY_change,CS_YOY_change,USSTHPI,YOY_change,Unemployment_Year_Avg,recession,avg_rate_for_year
57,1954,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.008333
58,1955,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.785000
59,1956,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.728333
60,1957,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.105000
61,1958,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.572500

In [11]:
# save it off
path = 'data/cleaned data/national_data_agg.csv'
merged_df.to_csv(path, index = False)